-- THIS MIGRATION IS OBSOLETE AND HAS BEEN SUPERSEDED BY 2024-07-31
-- Its contents have been merged into the newer migration file to ensure
-- a clean and correct update path. You do not need to run this file.
-- Please run src/lib/migration-2024-07-31.sql instead.
