-- This migration file is now deprecated and will be removed.
-- The master database-schema.sql file is now fully idempotent
-- and serves as the single source of truth for the schema.
-- Please use that file for any future database setup or updates.
