
'use client';

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { getAnomalyInsights } from '@/app/data-actions';
import { Lightbulb, AlertTriangle, CheckCircle } from 'lucide-react';
import { useState, useEffect } from 'react';
import { Skeleton } from '@/components/ui/skeleton';
import { useToast } from '@/hooks/use-toast';
import { getErrorMessage } from '@/lib/error-handler';
import type { Anomaly } from '@/types';
import { AppPage, AppPageHeader } from '@/components/ui/page';

function AnomalyCard({ anomaly }: { anomaly: Anomaly }) {
  const isRevenue = anomaly.anomaly_type === 'Revenue Anomaly';
  const currentValue = isRevenue ? anomaly.daily_revenue : anomaly.daily_customers;
  const averageValue = isRevenue ? anomaly.avg_revenue : anomaly.avg_customers;
  const deviation = Math.abs(currentValue - averageValue);
  const direction = currentValue > averageValue ? 'higher' : 'lower';
  
  return (
    <Card className="border-warning/50">
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-warning">
          <AlertTriangle className="h-5 w-5" />
          {anomaly.anomaly_type} on {new Date(anomaly.date).toLocaleDateString()}
        </CardTitle>
        <CardDescription>
          Detected significant deviation from the 30-day average.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-2">
        <p>
          On this day, the {isRevenue ? 'daily revenue' : 'customer count'} was{' '}
          <strong>{isRevenue ? `$${Number(currentValue).toLocaleString()}` : currentValue}</strong>, which is{' '}
          {averageValue > 0 ? ((deviation / averageValue) * 100).toFixed(1) : '100'}% {direction} than the average of{' '}
          {isRevenue ? `$${Number(averageValue).toLocaleString(undefined, {maximumFractionDigits: 0})}` : Number(averageValue).toLocaleString(undefined, {maximumFractionDigits: 0})}.
        </p>
      </CardContent>
    </Card>
  );
}

export default function InsightsPage() {
  const [anomalies, setAnomalies] = useState<Anomaly[]>([]);
  const [loading, setLoading] = useState(true);
  const { toast } = useToast();

  useEffect(() => {
    async function fetchInsights() {
      try {
        setLoading(true);
        const data = await getAnomalyInsights();
        setAnomalies(data);
      } catch (error) {
        toast({
          variant: 'destructive',
          title: 'Error Fetching Insights',
          description: getErrorMessage(error) || 'Could not load anomaly data.'
        });
      } finally {
        setLoading(false);
      }
    }
    fetchInsights();
  }, [toast]);

  return (
    <AppPage>
      <AppPageHeader
        title="Proactive Insights"
        description="The engine automatically scans your recent data for significant events or deviations from normal patterns."
      />
      
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Lightbulb className="h-5 w-5 text-primary" />
            Anomaly Detection
          </CardTitle>
          <CardDescription>
            These insights are generated by comparing recent activity to the 30-day average.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {loading ? (
            <div className="space-y-4">
              <Skeleton className="h-24 w-full" />
              <Skeleton className="h-24 w-full" />
            </div>
          ) : anomalies.length > 0 ? (
            anomalies.map((anomaly, index) => (
              <AnomalyCard key={index} anomaly={anomaly} />
            ))
          ) : (
            <div className="h-40 flex flex-col items-center justify-center text-center border-2 border-dashed rounded-lg">
              <CheckCircle className="h-12 w-12 text-muted-foreground" />
              <h3 className="mt-4 text-lg font-semibold">No Anomalies Found</h3>
              <p className="text-muted-foreground">Your recent business activity appears to be within normal parameters.</p>
            </div>
          )}
        </CardContent>
      </Card>
    </AppPage>
  );
}

    